/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package evidencia1;

import java.util.HashMap;
import java.awt.Color;
import javax.swing.JOptionPane;
import java.applet.AudioClip;
/**
 *
 * @author Alumno
 */
public class interfaz extends javax.swing.JFrame 
{
    estructuras datos = new estructuras();
    HashMap lista = new HashMap();
    
    Boolean colision1 = false;
    Boolean colision2 = false;
    Boolean colision3 = false;
    Boolean colision4 = false;
    Boolean colision5 = false;
    Boolean colision6 = false;
    
    String nom = "";
    String nom1 = "";
    int menu1 = 0;
        
    public HashMap getLista() {
        lista.put(nom, nom1);
        return lista;
    } 
    /**
     * Creates new form interfaz
     */
    public interfaz() 
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vender = new javax.swing.JButton();
        nombre = new javax.swing.JTextField();
        movil = new javax.swing.JTextField();
        asiento = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        asiento1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        asiento2 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        asiento3 = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        asiento4 = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        asiento5 = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        asiento6 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        eliminar = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        imprimir = new javax.swing.JTextPane();
        imagen = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        abono = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 240, 240));

        vender.setText("vender");
        vender.setToolTipText("");
        vender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                venderMouseClicked(evt);
            }
        });
        vender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venderActionPerformed(evt);
            }
        });

        movil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movilActionPerformed(evt);
            }
        });

        asiento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Asiento 1, precio 300", "Asiento 2, precio 300", "Asiento 3, precio 300", "Asiento 4, precio 1000", "Asiento 5, precio 1000", "Asiento 6, precio 1000" }));
        asiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asientoActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(asiento1);

        jScrollPane2.setViewportView(asiento2);

        jScrollPane3.setViewportView(asiento3);

        jScrollPane4.setViewportView(asiento4);

        jScrollPane5.setViewportView(asiento5);

        jScrollPane6.setViewportView(asiento6);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nombre");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Movil");

        eliminar.setText("cancelar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        salir.setText("salir");
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
        });
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("resultados");

        jScrollPane7.setViewportView(imprimir);

        imagen.setIcon(new javax.swing.ImageIcon("D:\\Hugo\\Documents\\NetBeansProjects\\evidencia1\\__render___anime_girl_8_by_mizumikid-d8beqdb.png")); // NOI18N

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jLabel4.setText("Estadio Kawaii");

        abono.setText("abono");
        abono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abonoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(99, 99, 99))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(movil, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(asiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(vender)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(eliminar)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(abono)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(189, 189, 189))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(72, 72, 72))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(movil, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(asiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vender)
                            .addComponent(eliminar)
                            .addComponent(abono)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void movilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_movilActionPerformed

    private void venderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venderActionPerformed

       nom = this.nombre.getText();
       nom = nom.replaceAll(" ", "");
       this.nombre.setText(null);
       nom1 = this.movil.getText();
       nom1 = nom1.replaceAll(" ", "");
       this.movil.setText(null);
       
        datos.getasiento(asiento.getSelectedItem().toString());
        
        lista.get(nom);
        lista.get(nom1);
         if(abono.isSelected()) {
        if(!(nom.length()==0)&&!(nom1.length()==0)){
        switch(asiento.getSelectedIndex()){
            case 0:
                if(colision1 == false){
                this.imprimir.setText("el nombre es: "+nom+"\n"+"\nel movil es: "+nom1+"\n\n"+datos.adr);
                this.asiento1.setBackground(Color.red);
                colision1 = true;
                }
                else{JOptionPane.showMessageDialog(null, "asiento ocupado");
                this.imprimir.setText(null);
                
                }
                break;
            case 1:
                if(colision2 == false){
                this.imprimir.setText("el nombre es: "+nom+"\n"+"\nel movil es: "+nom1+"\n\n"+datos.adr);
                this.asiento2.setBackground(Color.red);
                colision2 = true;
                }
                else{JOptionPane.showMessageDialog(null, "asiento ocupado");
                this.imprimir.setText(null);
                }
                break;
            case 2:
                 if(colision3 == false){
                this.imprimir.setText("el nombre es: "+nom+"\n"+"\nel movil es: "+nom1+"\n\n"+datos.adr);
                this.asiento3.setBackground(Color.red);
                colision3 = true;
                }
                else{JOptionPane.showMessageDialog(null, "asiento ocupado");
                this.imprimir.setText(null);
                 }
              
                break;
            case 3: 
                 if(colision4 == false){
                this.imprimir.setText("el nombre es: "+nom+"\n"+"\nel movil es: "+nom1+"\n\n"+datos.adr);
                this.asiento4.setBackground(Color.red);
                colision4 = true;
                }
                else{JOptionPane.showMessageDialog(null, "asiento ocupado");
                this.imprimir.setText(null);
                 }
               
                break;
            case 4:
                 if(colision5 == false){
                this.imprimir.setText("el nombre es: "+nom+"\n"+"\nel movil es: "+nom1+"\n\n"+datos.adr);
                this.asiento5.setBackground(Color.red);
                colision5 = true;
                }
                else{JOptionPane.showMessageDialog(null, "asiento ocupado");
                this.imprimir.setText(null);
                 }
               
                break;
            case 5:
                 if(colision6 == false){
                this.imprimir.setText("el nombre es: "+nom+"\n"+"\nel movil es: "+nom1+"\n\n"+datos.adr);
                this.asiento6.setBackground(Color.red);
                colision6 = true;
                }
                else{JOptionPane.showMessageDialog(null, "asiento ocupado");
                this.imprimir.setText(null);
                 }
                
                break;
                default:
                 this.imprimir.setText("error de aplicacion");
                    break;          
        }
        }
        else{JOptionPane.showMessageDialog(null, "datos vacios por favor ingreselos");}
         
         }else{
           JOptionPane.showMessageDialog(null, "abono no disponible no se puede vender asiento debe de esperar");  
         }
    
    }//GEN-LAST:event_venderActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        //System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void asientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asientoActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // metodo eliminar
       nom = this.nombre.getText();
       nom = nom.replaceAll(" ", "");
       this.nombre.setText(null);
       nom1 = this.movil.getText();
       nom1 = nom1.replaceAll(" ", "");
       this.movil.setText(null);
       
        datos.getasiento(asiento.getSelectedItem().toString());
        
        lista.get(nom);
        lista.get(nom1);
        if(!(nom.length()==0)&&!(nom1.length()==0)){
        switch(asiento.getSelectedIndex()){
            case 0:
                if(colision1 == true){
                this.imprimir.setText("Asiento 1 cancelado ");
                this.asiento1.setBackground(Color.white);
                colision1 = false;
                }
                else{JOptionPane.showMessageDialog(null, "asiento disponible no se puede cancelar");}
                
                break;
            case 1:
                if(colision2 == true){
                this.imprimir.setText("Asiento 2 cancelado ");
                this.asiento2.setBackground(Color.white);
                colision2 = false;
               }
               else{JOptionPane.showMessageDialog(null, "asiento disponible no se puede cancelar");}
                
                break;
            case 2:
                if(colision3 == true){
                this.imprimir.setText("Asiento 3 cancelado ");
                this.asiento3.setBackground(Color.white);
                colision3 = false;
                }
                else{JOptionPane.showMessageDialog(null, "asiento disponible no se puede cancelar");}
                
                break;
            case 3: 
                if(colision4 == true){
                this.imprimir.setText("Asiento 4 cancelado");
                this.asiento4.setBackground(Color.white);
                colision4 = false;
                }
                else{JOptionPane.showMessageDialog(null, "asiento disponible no se puede cancelar");}
               
                break;
            case 4:
                if(colision5 == true){
                this.imprimir.setText("Asiento 5 cancelado ");
                this.asiento5.setBackground(Color.white);
                colision5 = false;
                }
                else{JOptionPane.showMessageDialog(null, "asiento disponible no se puede cancelar");}
                
                break;
            case 5:
                if(colision6 == true){
                this.imprimir.setText("Asiento 6 cancelado ");
                this.asiento6.setBackground(Color.white);
                colision6 = false;
                }
                else{JOptionPane.showMessageDialog(null, "asiento disponible no se puede cancelar");}
   
                break;
                default:
                this.imprimir.setText("error de aplicacion");
                break;          
        }
        }else{JOptionPane.showMessageDialog(null, "datos vacios por favor ingreselos");}
    }//GEN-LAST:event_eliminarActionPerformed

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        
        try{
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/evidencia1/bye.wav"));
        sonido.play();
        Thread.sleep(1000);
        }catch(InterruptedException ex){}
        System.exit(0);
    }//GEN-LAST:event_salirMouseClicked

    private void abonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abonoActionPerformed
      
    }//GEN-LAST:event_abonoActionPerformed

    private void venderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_venderMouseClicked
     
    }//GEN-LAST:event_venderMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JCheckBox abono;
    public static javax.swing.JComboBox asiento;
    public static javax.swing.JTextPane asiento1;
    public static javax.swing.JTextPane asiento2;
    public static javax.swing.JTextPane asiento3;
    public static javax.swing.JTextPane asiento4;
    public static javax.swing.JTextPane asiento5;
    public static javax.swing.JTextPane asiento6;
    public static javax.swing.JButton eliminar;
    public static javax.swing.JLabel imagen;
    public static javax.swing.JTextPane imprimir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    public static javax.swing.JTextField movil;
    public static javax.swing.JTextField nombre;
    public static javax.swing.JButton salir;
    public static javax.swing.JButton vender;
    // End of variables declaration//GEN-END:variables
}
