/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tarea11;
import java.util.Random;
import java.applet.AudioClip;
import javax.swing.JOptionPane;

/**
 *
 * @author Alumno
 */
public class ventana extends javax.swing.JFrame {
   cronometro tiempo = new cronometro();
   ordenamientos orden = new ordenamientos();
   Random azar = new Random();
   int [] arreglo = new int [100];
   int [] arreglo2 = new int [1000];
   int [] arreglo3 = new int [10000];
   int x =0;
   int y = 0;
   
    /**
     * Creates new form ventana
     */
    public ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupodebotones = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        numero1 = new javax.swing.JRadioButton();
        numero2 = new javax.swing.JRadioButton();
        numero3 = new javax.swing.JRadioButton();
        generador = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tiempo1 = new javax.swing.JTextField();
        burbuja = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tiempo2 = new javax.swing.JTextField();
        selection = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tiempo3 = new javax.swing.JTextField();
        insertion = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tiempo4 = new javax.swing.JTextField();
        shell = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tiempo6 = new javax.swing.JTextField();
        merge = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tiempo5 = new javax.swing.JTextField();
        quick = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        numerosrandom = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        ordenados = new javax.swing.JTextArea();
        jPanel9 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Distintos Ordenamientos");

        jLabel2.setText("Generar numeros");

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));

        grupodebotones.add(numero1);
        numero1.setText("100");

        grupodebotones.add(numero2);
        numero2.setText("1000");

        grupodebotones.add(numero3);
        numero3.setText("10000");

        generador.setText("generar numero");
        generador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(generador, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(81, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(numero1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(numero2)
                        .addGap(35, 35, 35)
                        .addComponent(numero3)
                        .addGap(26, 26, 26))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numero1)
                    .addComponent(numero2)
                    .addComponent(numero3))
                .addGap(30, 30, 30)
                .addComponent(generador)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabel3.setText("Ordenamientos");

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        jLabel4.setText("bubble");

        jLabel6.setText("tiempo:");

        tiempo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiempo1ActionPerformed(evt);
            }
        });

        burbuja.setText("ordenar");
        burbuja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                burbujaActionPerformed(evt);
            }
        });

        jButton3.setText("limpiar ");
        jButton3.setMaximumSize(new java.awt.Dimension(71, 23));
        jButton3.setMinimumSize(new java.awt.Dimension(71, 23));
        jButton3.setPreferredSize(new java.awt.Dimension(71, 23));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(16, 16, 16)
                            .addComponent(tiempo1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(burbuja, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tiempo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(burbuja)
                .addGap(3, 3, 3)
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));

        jLabel5.setText("selection");

        jLabel7.setText("tiempo:");

        tiempo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiempo2ActionPerformed(evt);
            }
        });

        selection.setText("ordenar");
        selection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectionActionPerformed(evt);
            }
        });

        jButton4.setText("limpiar");
        jButton4.setMaximumSize(new java.awt.Dimension(71, 23));
        jButton4.setMinimumSize(new java.awt.Dimension(71, 23));
        jButton4.setPreferredSize(new java.awt.Dimension(71, 23));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tiempo2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(selection))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(tiempo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selection)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel8.setText("visualizar numeros al azar");

        jPanel4.setBackground(new java.awt.Color(0, 204, 204));

        jLabel11.setText("insertion");

        jLabel19.setText("tiempo:");

        insertion.setText("ordenar");
        insertion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertionActionPerformed(evt);
            }
        });

        jButton6.setText("limpiar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(insertion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tiempo3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tiempo3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(insertion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addGap(12, 12, 12))
        );

        jPanel5.setBackground(new java.awt.Color(0, 204, 204));

        jLabel12.setText("shell");

        jLabel15.setText("tiempo:");

        shell.setText("ordenar");
        shell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shellActionPerformed(evt);
            }
        });

        jButton7.setText("limpiar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(shell, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tiempo4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tiempo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shell)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(0, 204, 204));

        jLabel14.setText("merge");

        jLabel17.setText("tiempo:");

        merge.setText("ordenar");
        merge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mergeActionPerformed(evt);
            }
        });

        jButton9.setText("limpiar");
        jButton9.setMaximumSize(new java.awt.Dimension(71, 23));
        jButton9.setMinimumSize(new java.awt.Dimension(71, 23));
        jButton9.setPreferredSize(new java.awt.Dimension(71, 23));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(merge)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addGap(30, 30, 30)
                            .addComponent(tiempo6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel14)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tiempo6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(merge)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(0, 204, 204));

        jLabel13.setText("quick");

        jLabel16.setText("tiempo:");

        quick.setText("ordenar");
        quick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quickActionPerformed(evt);
            }
        });

        jButton8.setText("limpiar");
        jButton8.setMaximumSize(new java.awt.Dimension(71, 23));
        jButton8.setMinimumSize(new java.awt.Dimension(71, 23));
        jButton8.setOpaque(false);
        jButton8.setPreferredSize(new java.awt.Dimension(71, 23));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quick)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addComponent(jLabel16)
                            .addGap(30, 30, 30)
                            .addComponent(tiempo5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel13)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tiempo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quick)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel10.setText("visualizar numeros ordenados");

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tarea11/assets/little_busters___kamikita_komari_render_by_kawaiikuma_chan-d96r3cr.png"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        numerosrandom.setColumns(20);
        numerosrandom.setRows(5);
        jScrollPane1.setViewportView(numerosrandom);

        ordenados.setColumns(20);
        ordenados.setRows(5);
        jScrollPane2.setViewportView(ordenados);

        jPanel9.setBackground(new java.awt.Color(255, 51, 51));

        jButton1.setText("limpiar random");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("limpiar ordenados");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(30, 30, 30))
        );

        jPanel10.setBackground(new java.awt.Color(255, 204, 51));

        salir.setText("salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(59, 59, 59)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(123, 123, 123)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(33, 33, 33)
                                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(162, 162, 162)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(556, 556, 556)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(224, 224, 224))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tiempo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiempo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tiempo2ActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        try{
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/tarea11/assets/bye.wav"));
        sonido.play();
        Thread.sleep(1000);
        }catch(InterruptedException ex){}
        System.exit(0);
    
    }//GEN-LAST:event_salirActionPerformed

    private void generadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generadorActionPerformed
        
        //sonido
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/tarea11/assets/sectionpass.wav"));
        sonido.play();
       
       //generar los numeros con el jradio
        
       if(numero1.isSelected()){
           
              for(int i = 0; i < 100; i++){
    
                x = azar.nextInt(99);
                arreglo[i] = x;
                y = arreglo[i];
                
                
             }
               
              for(int i = 0; i < 100; i++){
    
                numerosrandom.append(String.valueOf(arreglo[i])+ ", ");
                if (i % 10==0){numerosrandom.append("\n");}
          }
           
       }
      else if(numero2.isSelected()){
           
          for(int i = 0; i < 1000; i++){
    
                x = azar.nextInt(99);
                arreglo2[i] = x;
                y = arreglo2[i];
                
                
             }
               
              for(int i = 0; i < 1000; i++){
    
                numerosrandom.append(String.valueOf(arreglo2[i])+ ", ");
                if (i % 32==0){numerosrandom.append("\n");}
          }
       
       }
      else if(numero3.isSelected()){
             for(int i = 0; i < 10000; i++){
    
                x = azar.nextInt(99);
                arreglo3[i] = x;
                y = arreglo3[i];
                
                
             }
               
              for(int i = 0; i < 10000; i++){
    
                numerosrandom.append(String.valueOf(arreglo3[i])+ ", ");
                if (i % 100==0){numerosrandom.append("\n");}
          }
       }
       if((!numero1.isSelected())&&(!numero2.isSelected())&&(!numero3.isSelected())){
           JOptionPane.showMessageDialog(this, "selecciona una opcion por favor");
       }
        
    }//GEN-LAST:event_generadorActionPerformed

    private void burbujaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_burbujaActionPerformed
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/tarea11/assets/sectionpass.wav"));
        sonido.play();
        
        //inicio de burbuja
        
        if(numero1.isSelected()){
       int aux;
        tiempo.start();
        for (int i = 1;i<10000000;i++) {}
        
          for(int i =0; i< arreglo.length;i++){
            for(int j =0; j< arreglo.length;j++){
                  
                 if ((arreglo[i]) > (arreglo[j]))
                {
                    aux = arreglo[i];
                    arreglo[i] = arreglo[j];
                    arreglo[j]= aux;
                    
                          
                }   
            }
            
        }
        tiempo.stop();
        tiempo1.setText(String.valueOf(tiempo.getMilliseconds()+"ms"));
        
            for (int k =0; k < 100; k++){
               ordenados.append(arreglo[k] +", "); 
            if(k % 10 == 0){
               ordenados.append("\n"); 
            }
                
        }
        
    }//GEN-LAST:event_burbujaActionPerformed
     if(numero2.isSelected()){
        int aux;
        tiempo.start();
        for (int i = 1;i<10000000;i++) {}
        
          for(int i =0; i< arreglo2.length;i++){
            for(int j =0; j< arreglo2.length;j++){
                  
                 if ((arreglo2[i]) > (arreglo2[j]))
                {
                    aux = arreglo2[i];
                    arreglo2[i] = arreglo2[j];
                    arreglo2[j]= aux;
                    
                          
                }   
            }
            
        }
        tiempo.stop();
        tiempo1.setText(String.valueOf(tiempo.getMilliseconds()+"ms"));
        
            for (int k =0; k < 1000; k++){
               ordenados.append(arreglo2[k] +", "); 
            if(k % 32 == 0){
               ordenados.append("\n"); 
            }
                
        }
   }
    if(numero3.isSelected()){
       int aux;
        tiempo.start();
        for (int i = 1;i<10000000;i++) {}
        
          for(int i =0; i< arreglo3.length;i++){
            for(int j =0; j< arreglo3.length;j++){
                  
                 if ((arreglo3[i]) > (arreglo3[j]))
                {
                    aux = arreglo3[i];
                    arreglo3[i] = arreglo3[j];
                    arreglo3[j]= aux;
                    
                          
                }   
            }
            
        }
        tiempo.stop();
        tiempo1.setText(String.valueOf(tiempo.getMilliseconds()+"ms"));
        
            for (int k =0; k < 10000; k++){
               ordenados.append(arreglo3[k] +", "); 
            if(k % 100 == 0){
               ordenados.append("\n"); 
            }
                
        }
   }
}
    private void selectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectionActionPerformed
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/tarea11/assets/sectionpass.wav"));
        sonido.play();
        
        
        if(numero1.isSelected()){
           int temp2;
           tiempo.start();
           for (int i = 1;i<10000000;i++) {}
           for(int i = 0; i< arreglo.length-1;i++){
               temp2 = i;
           for(int j = i+1; j< arreglo.length;j++){
               if((arreglo[j])< arreglo[temp2]){
                   temp2 = j;
               }
           }
           if(temp2 != i ){
               int aux = arreglo[temp2];
               arreglo[temp2] = arreglo[i];
               arreglo[i] = aux;
           }
        }
          tiempo.stop();
          tiempo2.setText(String.valueOf(tiempo.getMilliseconds()+"ms"));
        
            for (int k =0; k < 100; k++){
               ordenados.append(arreglo[k] +", "); 
            if(k % 10 == 0){
               ordenados.append("\n"); 
            }
                
        }
           
        }
        if(numero2.isSelected()){
           int temp2;
           tiempo.start();
           for (int i = 1;i<10000000;i++) {}
           for(int i = 0; i< arreglo2.length-1;i++){
               temp2 = i;
           for(int j = i+1; j< arreglo2.length;j++){
               if((arreglo2[j])< arreglo2[temp2]){
                   temp2 = j;
               }
           }
           if(temp2 != i ){
               int aux = arreglo2[temp2];
               arreglo2[temp2] = arreglo2[i];
               arreglo2[i] = aux;
           }
        }
          tiempo.stop();
          tiempo2.setText(String.valueOf(tiempo.getMilliseconds()+"ms"));
        
            for (int k =0; k < 1000; k++){
               ordenados.append(arreglo2[k] +", "); 
            if(k % 32 == 0){
               ordenados.append("\n"); 
            }
                
        }
       
      
        }
        if(numero3.isSelected()){
             int temp2;
           tiempo.start();
           for (int i = 1;i<10000000;i++) {}
           for(int i = 0; i< arreglo3.length-1;i++){
               temp2 = i;
           for(int j = i+1; j< arreglo3.length;j++){
               if((arreglo3[j])< arreglo3[temp2]){
                   temp2 = j;
               }
           }
           if(temp2 != i ){
               int aux = arreglo3[temp2];
               arreglo3[temp2] = arreglo3[i];
               arreglo3[i] = aux;
           }
        }
          tiempo.stop();
          tiempo2.setText(String.valueOf(tiempo.getMilliseconds()+"ms"));
        
            for (int k =0; k < 10000; k++){
               ordenados.append(arreglo3[k] +", "); 
            if(k % 100 == 0){
               ordenados.append("\n"); 
            }
                
        }
          
         
        }
    }//GEN-LAST:event_selectionActionPerformed

    private void tiempo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiempo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tiempo1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/tarea11/assets/ploss.wav"));
        sonido.play();
        
        tiempo1.setText("");
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/tarea11/assets/ploss.wav"));
        sonido.play();
        
        tiempo2.setText("");
       
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void insertionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertionActionPerformed
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/tarea11/assets/sectionpass.wav"));
        sonido.play();
     
        if(numero1.isSelected()){
           int aux, cont1, cont2;
           tiempo.start();
           for (int i = 1;i<10000000;i++) {} 
           for(cont1 = 1; cont1< arreglo.length;cont1++){
               aux = arreglo[cont1];
               for(cont2=cont1-1;cont2 >=0 && arreglo[cont2]>aux;cont2--){
                   arreglo[cont2+1]=arreglo[cont2];
                   arreglo[cont2]=aux;
               }
           }
          tiempo.stop();
          tiempo3.setText(String.valueOf(tiempo.getMilliseconds()+"ms"));
        
            for (int k =0; k < 100; k++){
               ordenados.append(arreglo[k] +", "); 
            if(k % 10 == 0){
               ordenados.append("\n"); 
            }
                
        }
           
        }
        if (numero2.isSelected()){
             int aux, cont1, cont2;
           tiempo.start();
           for (int i = 1;i<10000000;i++) {} 
           for(cont1 = 1; cont1< arreglo2.length;cont1++){
               aux = arreglo2[cont1];
               for(cont2=cont1-1;cont2 >=0 && arreglo2[cont2]>aux;cont2--){
                   arreglo2[cont2+1]=arreglo2[cont2];
                   arreglo2[cont2]=aux;
               }
           }
          tiempo.stop();
          tiempo3.setText(String.valueOf(tiempo.getMilliseconds()+"ms"));
        
            for (int k =0; k < 1000; k++){
               ordenados.append(arreglo2[k] +", "); 
            if(k % 32 == 0){
               ordenados.append("\n"); 
            }
                
        }
        }
        if(numero3.isSelected()){
             int aux, cont1, cont2;
           tiempo.start();
           for (int i = 1;i<10000000;i++) {} 
           for(cont1 = 1; cont1< arreglo3.length;cont1++){
               aux = arreglo3[cont1];
               for(cont2=cont1-1;cont2 >=0 && arreglo3[cont2]>aux;cont2--){
                   arreglo3[cont2+1]=arreglo3[cont2];
                   arreglo3[cont2]=aux;
               }
           }
          tiempo.stop();
          tiempo3.setText(String.valueOf(tiempo.getMilliseconds()+"ms"));
        
            for (int k =0; k < 10000; k++){
               ordenados.append(arreglo3[k] +", "); 
            if(k % 100 == 0){
               ordenados.append("\n"); 
            }
                
        }
        }
    }//GEN-LAST:event_insertionActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/tarea11/assets/ploss.wav"));
        sonido.play();
        
        tiempo3.setText("");
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/tarea11/assets/ploss.wav"));
        sonido.play();

        numerosrandom.setText(" ");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/tarea11/assets/ploss.wav"));
        sonido.play();

        ordenados.setText(" ");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/tarea11/assets/ploss.wav"));
        sonido.play();

        tiempo4.setText(" ");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void shellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shellActionPerformed
        
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/tarea11/assets/sectionpass.wav"));
        sonido.play();
        
        if(numero1.isSelected()){
           tiempo.start();
           for (int i = 1;i<10000000;i++) {} 
            for(int i = arreglo.length/2; i >0; i = (i==2)? 1:(int) Math.round(i/2.2)){
                for(int j = i; j < arreglo.length; j++){
                    for(int k = j; k >= i && arreglo[k - i]> arreglo[k]; k -= i){
                        int temp = arreglo[k];
                        arreglo[k]= arreglo[k-i];
                        arreglo[k-i] = temp;
                    }
                }
            }
            tiempo.stop();
            tiempo4.setText(String.valueOf(tiempo.getMilliseconds()+"ms"));
             for (int t =0; t < 100; t++){
               ordenados.append(arreglo[t] +", "); 
            if(t % 10 == 0){
               ordenados.append("\n"); 
            }
                
        }
        }
        if(numero2.isSelected()){
            tiempo.start();
           for (int i = 1;i<10000000;i++) {} 
            for(int i = arreglo2.length/2; i >0; i = (i==2)? 1:(int) Math.round(i/2.2)){
                for(int j = i; j < arreglo2.length; j++){
                    for(int k = j; k >= i && arreglo2[k - i]> arreglo2[k]; k -= i){
                        int temp = arreglo2[k];
                        arreglo2[k]= arreglo2[k-i];
                        arreglo2[k-i] = temp;
                    }
                }
            }
            tiempo.stop();
            tiempo4.setText(String.valueOf(tiempo.getMilliseconds()+"ms"));
             for (int t =0; t < 1000; t++){
               ordenados.append(arreglo2[t] +", "); 
            if(t % 32 == 0){
               ordenados.append("\n"); 
            }
                
        } 
        }
        if(numero3.isSelected()){
             tiempo.start();
           for (int i = 1;i<10000000;i++) {} 
            for(int i = arreglo3.length/2; i >0; i = (i==2)? 1:(int) Math.round(i/2.2)){
                for(int j = i; j < arreglo3.length; j++){
                    for(int k = j; k >= i && arreglo3[k - i]> arreglo3[k]; k -= i){
                        int temp = arreglo3[k];
                        arreglo3[k]= arreglo3[k-i];
                        arreglo3[k-i] = temp;
                    }
                }
            }
            tiempo.stop();
            tiempo4.setText(String.valueOf(tiempo.getMilliseconds()+"ms"));
             for (int t =0; t < 10000; t++){
               ordenados.append(arreglo3[t] +", "); 
            if(t % 100 == 0){
               ordenados.append("\n"); 
            }
                
        }
        }
    }//GEN-LAST:event_shellActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/tarea11/assets/ploss.wav"));
        sonido.play();

        tiempo5.setText(" ");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void quickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quickActionPerformed
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/tarea11/assets/sectionpass.wav"));
        sonido.play();
        
        if(numero1.isSelected()){
            int abajo = 0;
            int arriba = arreglo.length -1;
            tiempo.start();
            for (int i = 1;i<10000000;i++) {} 
            orden.quickSort(arreglo, abajo, arriba);
            for (int t =0; t < 100; t++){
               ordenados.append(arreglo[t] +", "); 
               tiempo.stop();
               tiempo5.setText(String.valueOf(tiempo.getMilliseconds()+"ms")); 
            if(t % 10 == 0){
               ordenados.append("\n"); 
            }
            }  
        }
        if(numero2.isSelected()){
            int abajo = 0;
            int arriba = arreglo2.length -1;
            tiempo.start();
            for (int i = 1;i<10000000;i++) {} 
            orden.quickSort(arreglo2, abajo, arriba);
            for (int t =0; t < 1000; t++){
               ordenados.append(arreglo2[t] +", "); 
               tiempo.stop();
               tiempo5.setText(String.valueOf(tiempo.getMilliseconds()+"ms"));
            if(t % 32 == 0){
               ordenados.append("\n"); 
            }
            }  
        }
        if(numero3.isSelected()){
            int abajo = 0;
            int arriba = arreglo3.length -1;
            tiempo.start();
            for (int i = 1;i<10000000;i++) {} 
            orden.quickSort(arreglo3, abajo, arriba);
            for (int t =0; t < 10000; t++){
               ordenados.append(arreglo3[t] +", "); 
               tiempo.stop();
               tiempo5.setText(String.valueOf(tiempo.getMilliseconds()+"ms"));
            if(t % 100 == 0){
               ordenados.append("\n"); 
            }
            }  
        }
        
    }//GEN-LAST:event_quickActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
       AudioClip sonido;
       sonido = java.applet.Applet.newAudioClip(getClass().getResource("/tarea11/assets/ploss.wav"));
       sonido.play();

       tiempo6.setText(" ");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void mergeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mergeActionPerformed
       
       AudioClip sonido;
       sonido = java.applet.Applet.newAudioClip(getClass().getResource("/tarea11/assets/sectionpass.wav"));
       sonido.play();
        
        
       if(numero1.isSelected()){
            tiempo.start();
            for (int i = 1;i<10000000;i++) {} 
            orden.mergeSort(arreglo);
            for (int t =0; t < 100; t++){
               ordenados.append(arreglo[t] +", "); 
               tiempo.stop();
               tiempo6.setText(String.valueOf(tiempo.getMilliseconds()+"ms"));
            if(t % 10 == 0){
               ordenados.append("\n"); 
            }
            }  
       }
       if(numero2.isSelected()){
            tiempo.start();
            for (int i = 1;i<10000000;i++) {} 
            orden.mergeSort(arreglo2);
            for (int t =0; t < 1000; t++){
               ordenados.append(arreglo2[t] +", "); 
               tiempo.stop();
               tiempo6.setText(String.valueOf(tiempo.getMilliseconds()+"ms"));
            if(t % 32 == 0){
               ordenados.append("\n"); 
            }
            } 
       }
       if(numero3.isSelected()){
            tiempo.start();
            for (int i = 1;i<10000000;i++) {} 
            orden.mergeSort(arreglo3);
            for (int t =0; t < 10000; t++){
               ordenados.append(arreglo3[t] +", "); 
               tiempo.stop();
               tiempo6.setText(String.valueOf(tiempo.getMilliseconds()+"ms"));
            if(t % 100 == 0){
               ordenados.append("\n"); 
            }
            } 
       }
    }//GEN-LAST:event_mergeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton burbuja;
    public javax.swing.JButton generador;
    public javax.swing.ButtonGroup grupodebotones;
    public javax.swing.JButton insertion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JButton merge;
    private javax.swing.JRadioButton numero1;
    private javax.swing.JRadioButton numero2;
    private javax.swing.JRadioButton numero3;
    public javax.swing.JTextArea numerosrandom;
    public javax.swing.JTextArea ordenados;
    public javax.swing.JButton quick;
    public javax.swing.JButton salir;
    public javax.swing.JButton selection;
    public javax.swing.JButton shell;
    public javax.swing.JTextField tiempo1;
    public javax.swing.JTextField tiempo2;
    public javax.swing.JTextField tiempo3;
    public javax.swing.JTextField tiempo4;
    public javax.swing.JTextField tiempo5;
    public javax.swing.JTextField tiempo6;
    // End of variables declaration//GEN-END:variables
}
