/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package evidencia2;

import javax.swing.JOptionPane;
import java.applet.AudioClip;


public class Ventana extends javax.swing.JFrame {

    ArbolBinario ab;
    Nodo a;
    boolean flag = true;

    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dato = new javax.swing.JTextField();
        ingresar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        buscar = new javax.swing.JButton();
        tamaño = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();
        dibujar = new javax.swing.JButton();
        preOrden = new javax.swing.JButton();
        inOrden = new javax.swing.JButton();
        postOrden = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        area.setColumns(20);
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(360, 350, 320, 80);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Arbol Binario");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(500, 51, 134, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Dato:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(340, 60, 35, 17);

        dato.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(dato);
        dato.setBounds(380, 60, 85, 20);

        ingresar.setBackground(new java.awt.Color(255, 102, 102));
        ingresar.setText("Ingresar");
        ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarActionPerformed(evt);
            }
        });
        getContentPane().add(ingresar);
        ingresar.setBounds(360, 100, 100, 23);

        eliminar.setBackground(new java.awt.Color(255, 102, 102));
        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(eliminar);
        eliminar.setBounds(470, 100, 80, 23);

        buscar.setBackground(new java.awt.Color(255, 102, 102));
        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        getContentPane().add(buscar);
        buscar.setBounds(570, 100, 100, 23);

        tamaño.setBackground(new java.awt.Color(255, 102, 102));
        tamaño.setText("Tamaño");
        tamaño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tamañoActionPerformed(evt);
            }
        });
        getContentPane().add(tamaño);
        tamaño.setBounds(360, 180, 100, 20);

        limpiar.setBackground(new java.awt.Color(255, 102, 102));
        limpiar.setText("Limpiar");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(limpiar);
        limpiar.setBounds(470, 180, 80, 20);

        dibujar.setBackground(new java.awt.Color(255, 102, 102));
        dibujar.setText("Dibujar");
        dibujar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dibujarActionPerformed(evt);
            }
        });
        getContentPane().add(dibujar);
        dibujar.setBounds(570, 180, 100, 20);

        preOrden.setBackground(new java.awt.Color(255, 102, 102));
        preOrden.setText("PreOrden");
        preOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preOrdenActionPerformed(evt);
            }
        });
        getContentPane().add(preOrden);
        preOrden.setBounds(360, 140, 100, 20);

        inOrden.setBackground(new java.awt.Color(255, 102, 102));
        inOrden.setText("InOrden");
        inOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inOrdenActionPerformed(evt);
            }
        });
        getContentPane().add(inOrden);
        inOrden.setBounds(470, 140, 80, 20);

        postOrden.setBackground(new java.awt.Color(255, 102, 102));
        postOrden.setText("PostOrden");
        postOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postOrdenActionPerformed(evt);
            }
        });
        getContentPane().add(postOrden);
        postOrden.setBounds(570, 140, 100, 23);

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setForeground(new java.awt.Color(153, 0, 0));
        jButton1.setText("salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 30, 130, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/evidencia2/assets/_wallpaper__kawaii_face_pink_by_kawaistore-d7d2nmg.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(3, 1, 1060, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarActionPerformed

        int b = 0;
        
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/evidencia2/assets/sectionpass.wav"));
        sonido.play();
        
        if (dato.getText().length() > 0) {
            try {
                b = Integer.parseInt(dato.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "El valor no es un numero");
            }

            if (b != 0) {
                a = new Nodo(b);

                if (flag == true) {
                    ab = new ArbolBinario(Integer.valueOf(dato.getText()));
                    flag = false;
                } else {
                    ab.Add(a, ab.raiz);
                }
                JOptionPane.showMessageDialog(this, "Dato agregado");
            }

        } else {
            JOptionPane.showMessageDialog(this, "El campo esta vacio");
        }

        dato.setText("");
        
    }//GEN-LAST:event_ingresarActionPerformed

    private void dibujarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dibujarActionPerformed
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/evidencia2/assets/sectionpass.wav"));
        sonido.play();
        area.setText(ab.imprimir(0, ab.raiz));
    }//GEN-LAST:event_dibujarActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/evidencia2/assets/sectionpass.wav"));
        sonido.play();
        area.setText("");
    }//GEN-LAST:event_limpiarActionPerformed

    private void preOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preOrdenActionPerformed
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/evidencia2/assets/sectionpass.wav"));
        sonido.play();
        area.setText(ab.imprimir(0, ab.raiz));
    }//GEN-LAST:event_preOrdenActionPerformed

    private void inOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inOrdenActionPerformed
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/evidencia2/assets/sectionpass.wav"));
        sonido.play();
        area.setText(ab.imprimir(1, ab.raiz));
    }//GEN-LAST:event_inOrdenActionPerformed

    private void postOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postOrdenActionPerformed
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/evidencia2/assets/sectionpass.wav"));
        sonido.play();
        area.setText(ab.imprimir(2, ab.raiz));
    }//GEN-LAST:event_postOrdenActionPerformed

    private void tamañoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tamañoActionPerformed
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/evidencia2/assets/sectionpass.wav"));
        sonido.play();
        area.setText(String.valueOf(ab.Size()));
    }//GEN-LAST:event_tamañoActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/evidencia2/assets/sectionpass.wav"));
        sonido.play();
        int a = 0;
        if (dato.getText().length() > 0) {
            try {
                a = Integer.parseInt(dato.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "El valor no es un numero");
            }
            if (a != 0) {
                ab.borrar(a);
            }
        } else {
            JOptionPane.showMessageDialog(this, "El campo esta vacio");
        }

        dato.setText("");
    }//GEN-LAST:event_eliminarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed

        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/evidencia2/assets/sectionpass.wav"));
        sonido.play();
        int a = 0;
        if (dato.getText().length() > 0) {
            try {
                a = Integer.parseInt(dato.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "El valor no es un numero");
            }
            if (a != 0) {
                boolean c = ab.buscar(a);
                dato.setText("");

                if (c == true) {
                    area.setText("Dato: " + a + " si existe");
                } else {
                    area.setText("Dato: " + a + " no existe");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "El campo esta vacio");
        }

        dato.setText("");



    }//GEN-LAST:event_buscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try{
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/evidencia2/assets/bye.wav"));
        sonido.play();
        Thread.sleep(1000);
        }catch(InterruptedException ex){}
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JButton buscar;
    private javax.swing.JTextField dato;
    private javax.swing.JButton dibujar;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton inOrden;
    private javax.swing.JButton ingresar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpiar;
    private javax.swing.JButton postOrden;
    private javax.swing.JButton preOrden;
    private javax.swing.JButton tamaño;
    // End of variables declaration//GEN-END:variables
}
