/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juegoev3;
import java.applet.AudioClip;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import java.util.Random;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
/**
 *
 * @author Hugo
 */
public class juegoventana extends javax.swing.JFrame {
    
    JLabel[][] arreglo1 = new JLabel[10][10];
    int [][]  arreglo2 = new int [10][10];
    Random azar = new Random();
    boolean cooler = true;
    sonido sony = new sonido(null);
    int punto = 0; 
    int hora = 0, minuto = 0,segundo = 0,ms=0;
    Timer t;
    int op = 1;
    
//cronometro
    ActionListener acciones = new ActionListener() {

        @Override
        public void actionPerformed(ActionEvent ae) {
            ms++;
            if(ms == 100){
                ms = 0;
                ++segundo;
            }
            if(segundo == 60){
                segundo = 0;
                ++minuto;
            }
            if(minuto == 60){
                minuto = 0;
                ++hora;
            }
            actualizartiempo();
        }
    };
  
    private void actualizartiempo(){
        String tiempo = (hora<=9?"0":"")+hora+":"+(minuto<=9?"0":"")+minuto+":"+(segundo<=9?"0":"")+segundo+":"+(ms<=9?"0":"")+ms;
        time2.setText(tiempo);
    }
    
 //recursividad   
  public void recursivo(int px,int py, int color){
        if(color != -1)
        {arreglo2[px][py] = -1;}
        if (color == -1)
        {
        arreglo2[px][py] = -2;   
        arreglo1[px][py].setIcon(new ImageIcon("imagenes/"+arreglo2[px][py]+".jpg"));
        }
        if(px < 9 && arreglo2[px+1][py] == color)
        {
            recursivo(px+1, py, color);  
        }
        if(px > 0 && arreglo2[px-1][py]== color)
        {
            recursivo(px-1, py, color);
        }
        if(py < 9 && arreglo2[px][py+1] == color)
        {
            recursivo(px, py+1, color);
        }
        if(py > 0 && arreglo2[px][py-1]== color)
        {
            recursivo(px, py-1, color);
        }
    }
  
    public juegoventana() {
        initComponents();
        setLocationRelativeTo(null);
        t = new Timer(10, acciones);
        sony.sound1.loop();
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dato2 = new javax.swing.JInternalFrame();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        iniciar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        creditos = new javax.swing.JButton();
        equipo = new javax.swing.JButton();
        score = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        time2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nivel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dato2.setPreferredSize(new java.awt.Dimension(518, 540));
        dato2.setRequestFocusEnabled(false);
        dato2.setVisible(true);
        dato2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dato2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegoev3/assets/tumblr_nahqypG35E1slreixo1_500.jpg"))); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(518, 540));

        javax.swing.GroupLayout dato2Layout = new javax.swing.GroupLayout(dato2.getContentPane());
        dato2.getContentPane().setLayout(dato2Layout);
        dato2Layout.setHorizontalGroup(
            dato2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
        );
        dato2Layout.setVerticalGroup(
            dato2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dato2Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));

        iniciar.setBackground(new java.awt.Color(153, 153, 255));
        iniciar.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        iniciar.setText("Iniciar");
        iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        jButton1.setText("Finalizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        creditos.setBackground(new java.awt.Color(153, 153, 255));
        creditos.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        creditos.setText("Creditos");
        creditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditosActionPerformed(evt);
            }
        });

        equipo.setBackground(new java.awt.Color(153, 153, 255));
        equipo.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        equipo.setText("Equipo");
        equipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(creditos)
                .addGap(18, 18, 18)
                .addComponent(equipo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(equipo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(creditos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        score.setBackground(new java.awt.Color(240, 240, 240));
        score.setFont(new java.awt.Font("Yu Gothic Medium", 0, 24)); // NOI18N
        score.setText("0");
        score.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoreActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        jLabel1.setText("Score:");

        time2.setBackground(new java.awt.Color(240, 240, 240));
        time2.setFont(new java.awt.Font("Yu Gothic Medium", 0, 24)); // NOI18N
        time2.setText("00:00:00:00");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        jLabel2.setText("Time:");

        nivel.setBackground(new java.awt.Color(240, 240, 240));
        nivel.setFont(new java.awt.Font("Yu Gothic Medium", 0, 24)); // NOI18N
        nivel.setText("0");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        jLabel4.setText("Level:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dato2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(score, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(time2, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(nivel))))
                .addContainerGap(23, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(score, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(time2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nivel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addComponent(dato2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarActionPerformed
        
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/juegoev3/assets/applause.wav"));
        sonido.play();
        
        jLabel3.setVisible(false);
        t.start();
        sony.sound1.stop();
        sony.sound2.loop();
        
        if(cooler == true){
	dato2.setBounds(0,0,518,540);
        dato2.setLayout(null);
	dato2.setDefaultCloseOperation(JInternalFrame.EXIT_ON_CLOSE);
        
        
        for (int i = 0; i < arreglo1.length; i++) {
            for (int j = 0; j < arreglo1.length; j++) {
                arreglo1[i][j] = new JLabel();
                arreglo1[i][j].setBounds(0+i*50,0+j*50,50,50);
                arreglo2[i][j] = azar.nextInt(4)+1;
                arreglo1[i][j].setIcon(new ImageIcon("imagenes/"+arreglo2[i][j]+".jpg"));
                arreglo1[i][j].setVisible(true);
                dato2.add(arreglo1[i][j]);
                
            }
            
        }  
        cooler = false;
       }
        else{
            JOptionPane.showMessageDialog(null, "juego ya iniciado");
        }
        
    }//GEN-LAST:event_iniciarActionPerformed

    private void dato2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dato2MouseClicked
             
            for (int i = 0; i < arreglo1.length; i++) {
            for (int j = 0; j < arreglo1.length; j++) {
              
                //invocar con el clic
                arreglo1[i][j].addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseClicked (MouseEvent ev){
                         
                        for (int k = 0; k < arreglo1.length; k++) {
                            for (int l = 0; l < arreglo1.length; l++) {
                                 if(arreglo1[k][l] == ev.getSource()){
                                     recursivo(k, l, arreglo2[k][l]);
                            }}}
                        
                        // ordenamiento burbuja
                        for (int k = 0; k < arreglo1.length; k++) {
                        for (int l = 0; l < arreglo1.length; l++) {
                            for (int m = 0; m < arreglo1.length; m++) {
                                if(m > 0 && arreglo2[l][m] == -2){
                                    arreglo2[l][m] = arreglo2[l][m-1];
                                    arreglo2[l][m-1] = -2;
                                  
                                }
                                arreglo1[l][m].setIcon(new ImageIcon("imagenes/"+arreglo2[l][m]+".jpg"));
                                punto++;
                            }}}
                        
                        //metodo loop
                        for (int k = 0; k < arreglo1.length; k++) {
                            for (int l = 0; l < arreglo1.length; l++) {
                                if(arreglo2[k][l] == -2){
                                      for (int kl = 0; kl < arreglo1.length; kl++) {
                                        for (int ll = 0; ll < arreglo1.length; ll++) {
                                            for (int m = 0; m < arreglo1.length; m++) {
                                                if(m > 0 && arreglo2[ll][m] == -2){
                                                    arreglo2[ll][m] = arreglo2[ll][m-1];
                                                    arreglo2[ll][m-1] = -2;
                                                    arreglo1[k][l] = new JLabel();
                                                    arreglo1[k][l].setBounds(0+k*50,0+l*50,50,50);
                                                    arreglo2[k][l] = azar.nextInt(4)+1;
                                                    arreglo1[k][l].setVisible(true);
                                                    dato2.add(arreglo1[k][l]);
                                }
                                arreglo1[ll][m].setIcon(new ImageIcon("imagenes/"+arreglo2[ll][m]+".jpg"));
                                punto++;
                            }}}}}}
                        
                        //score
                        for (int k = 0; k < arreglo1.length; k++) {
                            for (int l = 0; l < arreglo1.length; l++) {
                                
                                if(arreglo2[k][l] == 1){
                                    punto = punto + 23;
                                    score.setText(String.valueOf(punto));
                                }
                                else if(arreglo2[k][l] == 2){
                                    punto = punto + 44;
                                    score.setText(String.valueOf(punto));
                                }
                                else if(arreglo2[k][l] == 3){
                                    punto = punto + 66;
                                    score.setText(String.valueOf(punto));
                                }
                                else if(arreglo2[k][l] == 4){
                                    punto = punto + 22;
                                    score.setText(String.valueOf(punto));
                                }
                                
                                //niveles
                                if(punto >= 100000) {
                                    nivel.setText(String.valueOf("1"));
                                if(punto >= 500000){
                                    nivel.setText(String.valueOf("2"));
                                if(punto >= 1000000){
                                    nivel.setText(String.valueOf("3"));
                                if(punto >= 1500000){
                                    nivel.setText(String.valueOf("4")); 
                                if(punto >= 2000000){
                                    nivel.setText(String.valueOf("5")); 
                                if(punto >= 2500000){
                                    nivel.setText(String.valueOf("6"));
                                    JOptionPane.showMessageDialog(null, "lograste pasar los 6 niveles felicidades eres todo un sensei\n\n\n Game over");
                                      try{
                                            AudioClip sonido;
                                            sonido = java.applet.Applet.newAudioClip(getClass().getResource("/juegoev3/assets/42.wav"));
                                            sonido.play();
                                            Thread.sleep(1200);
                                            }catch(InterruptedException ex){}
                                             System.exit(0);
                                    }}}}}}}}
                        
                        
                        
                        // preguntas del juego
                          if (punto >= 100000 && op == 1 ) {
                          int seleccion = JOptionPane.showOptionDialog(
                            null,
                            "Te gusta jugar League of Legends?", 
                            "pregunta 1",
                            JOptionPane.YES_NO_CANCEL_OPTION,
                            JOptionPane.QUESTION_MESSAGE,
                            null,    
                            new Object[] { "si", "no", "que es eso?" },   
                            "si");

                            if (seleccion == 0){
                            AudioClip sonido;
                            sonido = java.applet.Applet.newAudioClip(getClass().getResource("/juegoev3/assets/llora.wav"));
                            sonido.play();
                            JOptionPane.showMessageDialog(null, "te gusta eso pues vete a jugarlo: game over");
                               System.exit(0);
                            }
                            else if(seleccion == 1){
                             AudioClip sonido;
                             sonido = java.applet.Applet.newAudioClip(getClass().getResource("/juegoev3/assets/56_1.wav"));
                             sonido.play();
                             JOptionPane.showMessageDialog(null, "respuesta correcta: bien hecho!");
                            }
                            else{
                             AudioClip sonido;
                             sonido = java.applet.Applet.newAudioClip(getClass().getResource("/juegoev3/assets/27.wav"));
                             sonido.play();
                             JOptionPane.showMessageDialog(null, "Es mejor no saberlo.");  
                            }
                            op = 2;
                            }
                          if(punto >= 500000 && op == 2){
                            int seleccion = JOptionPane.showOptionDialog(
                            null,
                            "Que edad tienes?", 
                            "pregunta 2",
                            JOptionPane.YES_NO_CANCEL_OPTION,
                            JOptionPane.QUESTION_MESSAGE,
                            null,    
                            new Object[] { "menos de 10 años", "entre 10 y 15 años", "tengo mas de 18" },   
                            "si");

                            if (seleccion == 0){
                            AudioClip sonido;
                            sonido = java.applet.Applet.newAudioClip(getClass().getResource("/juegoev3/assets/llora.wav"));
                            sonido.play();
                            JOptionPane.showMessageDialog(null, "lo siento eres menor de edad: game over");
                            System.exit(0);
                            }
                            else if(seleccion == 1){
                            AudioClip sonido;
                            sonido = java.applet.Applet.newAudioClip(getClass().getResource("/juegoev3/assets/llora.wav"));
                            sonido.play();
                            JOptionPane.showMessageDialog(null, "sigues siendo menor de edad: game over");
                            System.exit(0);
                            }
                            else{
                             AudioClip sonido;
                             sonido = java.applet.Applet.newAudioClip(getClass().getResource("/juegoev3/assets/56_1.wav"));
                             sonido.play();
                             JOptionPane.showMessageDialog(null, "eres mayor de edad vas por buen camino");  
                            }
                              op = 3;
                          }
                          if(punto>= 1000000 && op == 3){
                            int seleccion = JOptionPane.showOptionDialog(
                            null,
                            "De que sexo eres?", 
                            "pregunta 3",
                            JOptionPane.YES_NO_CANCEL_OPTION,
                            JOptionPane.QUESTION_MESSAGE,
                            null,    
                            new Object[] { "hombre", "mujer", "indefinido" },   
                            "si");

                            if (seleccion == 0){
                            AudioClip sonido;
                            sonido = java.applet.Applet.newAudioClip(getClass().getResource("/juegoev3/assets/56_1.wav"));
                            sonido.play();
                            JOptionPane.showMessageDialog(null, "eres hombre");
                            
                            }
                            else if(seleccion == 1){
                            AudioClip sonido;
                            sonido = java.applet.Applet.newAudioClip(getClass().getResource("/juegoev3/assets/56_1.wav"));
                            sonido.play();
                            JOptionPane.showMessageDialog(null, "eres mujer");
                            
                            }
                            else{
                             AudioClip sonido;
                             sonido = java.applet.Applet.newAudioClip(getClass().getResource("/juegoev3/assets/llora.wav"));
                             sonido.play();
                             JOptionPane.showMessageDialog(null, "si no eres hombre ni mujer entonces no eres humano por lo tanto: game over");
                             System.exit(0);
                            }
                            op = 4;
                          }
                          if(punto >= 1500000 && op == 4){
                            int seleccion = JOptionPane.showOptionDialog(
                            null,
                            "eres un Weeaboo?", 
                            "pregunta 4",
                            JOptionPane.YES_NO_CANCEL_OPTION,
                            JOptionPane.QUESTION_MESSAGE,
                            null,    
                            new Object[] { "si", "no", "no puedo contestar" },   
                            "si");

                            if (seleccion == 0){
                            AudioClip sonido;
                            sonido = java.applet.Applet.newAudioClip(getClass().getResource("/juegoev3/assets/56_1.wav"));
                            sonido.play();
                            JOptionPane.showMessageDialog(null, "felicidades eres todo un wapanese");
                            
                            }
                            else if(seleccion == 1){
                            AudioClip sonido;
                            sonido = java.applet.Applet.newAudioClip(getClass().getResource("/juegoev3/assets/llora.wav"));
                            sonido.play();
                            JOptionPane.showMessageDialog(null, "lastima pero este juego se trata de la cultura japonesa por lo tanto: game over");
                            System.exit(0);
                            }
                            else{
                             AudioClip sonido;
                             sonido = java.applet.Applet.newAudioClip(getClass().getResource("/juegoev3/assets/llora.wav"));
                             sonido.play();
                             JOptionPane.showMessageDialog(null, "si no eres honesto contigo mismo no podras avanzar: game over");
                             System.exit(0);
                            }
                              op = 5;
                          }
                          if(punto >= 2000000 && op == 5){
                               int seleccion = JOptionPane.showOptionDialog(
                            null,
                            "tienes waifu o husbando?", 
                            "pregunta 5",
                            JOptionPane.YES_NO_CANCEL_OPTION,
                            JOptionPane.QUESTION_MESSAGE,
                            null,    
                            new Object[] { "si", "no", "no puedo contestar" },   
                            "si");

                            if (seleccion == 0){
                            AudioClip sonido;
                            sonido = java.applet.Applet.newAudioClip(getClass().getResource("/juegoev3/assets/56_1.wav"));
                            sonido.play();
                            JOptionPane.showMessageDialog(null, "te felicito");
                            
                            }
                            else if(seleccion == 1){
                            AudioClip sonido;
                            sonido = java.applet.Applet.newAudioClip(getClass().getResource("/juegoev3/assets/llora.wav"));
                            sonido.play();
                            JOptionPane.showMessageDialog(null, "que triste");
                            
                            }
                            else{
                             AudioClip sonido;
                             sonido = java.applet.Applet.newAudioClip(getClass().getResource("/juegoev3/assets/llora.wav"));
                             sonido.play();
                             JOptionPane.showMessageDialog(null, "si no eres honesto contigo mismo no podras avanzar: game over");
                             System.exit(0);
                            }
                              op = 6;
                          }
                          
                        
                    }});}}
                    dato2.setVisible(true);     
                                   
       
    }//GEN-LAST:event_dato2MouseClicked

    private void creditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditosActionPerformed
         AudioClip sonido;
         sonido = java.applet.Applet.newAudioClip(getClass().getResource("/juegoev3/assets/applause.wav"));
         sonido.play();
        JOptionPane.showMessageDialog(null, "creditos: a 1iber 1iber por el tutorial que sirvio para el desarrollo de este juego: \nhttps://www.youtube.com/watch?v=XEibCH5lb4U"
                + "\n\ncreditos: a mike73 por la java class de audio para reproducir musica:\nhttp://www.dreamincode.net/forums/topic/343804-how-to-add-background-music-to-my-2d-platformer-game/"
                + "\n\ncreditos: a programacion y mas por el tutorial de las clases cronometro: \nhttps://www.youtube.com/watch?v=BUQcPgVTfhE"
        );
    }//GEN-LAST:event_creditosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           try{
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/juegoev3/assets/applause.wav"));
        sonido.play();
        Thread.sleep(1600);
        }catch(InterruptedException ex){}
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void scoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scoreActionPerformed

    private void equipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipoActionPerformed
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/juegoev3/assets/applause.wav"));
        sonido.play();
        
        JOptionPane.showMessageDialog(null, "Natalie Anaid Montes Serrano\n\n Nayeli Belen Montes Serrano\n\n Hugo Eduardo Matos Uribe");
    }//GEN-LAST:event_equipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(juegoventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(juegoventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(juegoventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(juegoventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new juegoventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton creditos;
    public javax.swing.JInternalFrame dato2;
    public javax.swing.JButton equipo;
    public javax.swing.JButton iniciar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField nivel;
    public javax.swing.JTextField score;
    public javax.swing.JTextField time2;
    // End of variables declaration//GEN-END:variables
}
